on:
  push:
    # Pattern matched against refs/tags
    branches:
      - main
    

name: Publish

jobs:
  ensure_cargo_fmt:
    name: Ensure 'cargo fmt' has been run
    runs-on: ubuntu-20.04
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
        profile: minimal
        components: rustfmt
    - uses: actions/checkout@v2
    - run: cargo fmt -- --check
  
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}